In [1]:
import numpy as np
import math

# №1

In [2]:
print(np.diag([1, 2, 3, 4], -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# №2

In [3]:
a=np.random.random((10, 3))
print(a, '\n', a[range(10), np.abs(a - 0.5).argmin(axis=1)])

[[0.47856928 0.34819496 0.14799753]
 [0.45224615 0.74006133 0.57072088]
 [0.75150217 0.51337856 0.70535236]
 [0.17428112 0.29511667 0.87572993]
 [0.14796429 0.59283264 0.42878633]
 [0.92643816 0.05687143 0.91190199]
 [0.75929908 0.26216721 0.85319571]
 [0.64582407 0.63611868 0.76457547]
 [0.87236421 0.38469158 0.72022892]
 [0.46092878 0.80366146 0.27033579]] 
 [0.47856928 0.45224615 0.51337856 0.29511667 0.42878633 0.91190199
 0.26216721 0.63611868 0.38469158 0.46092878]


# №3

In [4]:
a = np.random.random((6, 6))
print(a,np.sum(a, axis=1)/np.amax(a,axis=0))

[[0.72582629 0.99306449 0.02938739 0.06497563 0.51046025 0.15309876]
 [0.76432514 0.72927599 0.81576132 0.89074686 0.0349263  0.89105415]
 [0.81587809 0.74621278 0.1715113  0.48088276 0.78442598 0.4705025 ]
 [0.55500892 0.88782274 0.9871009  0.87164282 0.6806535  0.56807489]
 [0.68349208 0.31559476 0.56790308 0.32240409 0.74962226 0.45129227]
 [0.60874463 0.54229955 0.18780173 0.75370989 0.41995872 0.01367992]] [3.03576335 4.15490615 3.51475053 5.10841404 3.93957953 2.83506276]


# №4

In [5]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(np.max(x[1:][(x==0)[:-1]]))

5


# №5

In [6]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(len(i)) :
    x[i[j]]+=1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


# №6

1) np.round(array)

2) np.around(array)

# №7

In [42]:
from sklearn.datasets import fetch_openml
images, labels = fetch_openml('mnist_784', return_X_y=True, as_frame=False)
def kNN(train_X, train_Y, test_X, k):
    return  np.vectorize(lambda ii: str(np.bincount(train_Y[np.argsort(np.vectorize(lambda i, j: np.linalg.norm(test_X[i]-train_X[j]))(ii, range(len(train_X))))[:k]].astype(int)).argmax()))(range(len(test_X)))

# №8

In [48]:
train_size = 300
train_images = images[:train_size]
train_labels = labels[:train_size]
test_size = 100
test_images = images[-test_size:]
test_labels = labels[-test_size:]
def accuracy(Number_true, Number_result):
    acc = 0
    for i in range(len(Number_true)):
        if Number_true[i] == Number_result[i]:
            acc += 1
    return acc/len(Number_true)
max = -1
for l in range(1,200):
    if accuracy(test_labels, kNN(train_images, train_labels, test_images, l)) > max:
        max = accuracy(test_labels, kNN(train_images, train_labels, test_images, l))
        k = l
print("Результат:",kNN(train_images, train_labels, test_images, k))
print("Истинные номера:",test_labels)
print("Точность:",max)
print("Оптимальное k:",k)

Результат: ['8' '9' '0' '1' '5' '7' '4' '5' '6' '7' '8' '0' '1' '2' '3' '4' '7' '8'
 '4' '7' '8' '6' '9' '1' '4' '5' '8' '4' '4' '7' '0' '1' '9' '2' '8' '7'
 '8' '2' '6' '0' '6' '5' '3' '3' '8' '9' '1' '4' '0' '6' '1' '0' '0' '0'
 '3' '1' '1' '7' '7' '5' '4' '6' '0' '7' '0' '3' '6' '8' '7' '1' '5' '2'
 '4' '4' '4' '2' '6' '4' '1' '7' '3' '6' '5' '0' '1' '7' '3' '4' '5' '6'
 '7' '0' '4' '0' '1' '2' '3' '4' '5' '6']
Истинные номера: ['8' '9' '0' '1' '2' '3' '4' '5' '6' '7' '8' '0' '1' '2' '3' '4' '7' '8'
 '9' '7' '8' '6' '4' '1' '9' '3' '8' '4' '4' '7' '0' '1' '9' '2' '8' '7'
 '8' '2' '6' '0' '6' '5' '3' '3' '3' '9' '1' '4' '0' '6' '1' '0' '0' '6'
 '2' '1' '1' '7' '7' '8' '4' '6' '0' '7' '0' '3' '6' '8' '7' '1' '5' '2'
 '4' '9' '4' '3' '6' '4' '1' '7' '2' '6' '5' '0' '1' '2' '3' '4' '5' '6'
 '7' '8' '9' '0' '1' '2' '3' '4' '5' '6']
Точность: 0.84
Оптимальное k: 2
